<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Mini Shop Admin'. $this->translate('Mini Shop Admin'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
   <div id="wrap">
<div id="header">Mini Shop Admin</div>
<div id="nav">
<ul>
<li><a href="<?php echo $this->url("admin", array('action'=>'index'), array(), true); ?>">Home</a></li>
<li><a href="<?php echo $this->url("category", array('action'=>'index'), array(), true); ?>">Category</a></li>
<li><a href="<?php echo $this->url("product", array('action'=>'index'), array(), true); ?>">Product</a></li>
<li><a href="<?php echo $this->url("user", array('action'=>'index'), array(), true); ?>">User</a></li>

</ul>
</div>
<div id="main">
<div id="content">
<?php echo $this->content; ?>
          
<div id="footer">
<p>&nbsp;</p>
</div>
</div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
