<?php
$title = 'MiniShop - Administration';
$this->headTitle($title);
?>

<p>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('category', array('action' => 'add')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('category'));
echo $this->formRow($form->get('parentid'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>
</p>
</div>
<div id="sidebar">
<p><b>Menus</b></p>
<ul>
<li><a href="<?php echo $this->url("category", array('action' => 'add'), array(), true); ?>">Add</a></li>
<li><a href="<?php echo $this->url("category", array('action' => 'edit'), array(), true); ?>">Edit</a></li>
<li><a href="<?php echo $this->url("category", array('action' => 'delete'), array(), true); ?>">Delete</a></li>

</ul>
</div>
