<?php
$title = 'MiniShop - Administration - Category';
$this->headTitle($title);
?>

<table style="width:75%; text-align:center;">
<?php 
foreach($categories as $category){

	echo '<tr><td>' . $category->category . '</td>';
	echo '<td><a href="'. $this->url("category", array('action'=>'edit', 'id'=>$category->id), array(), true) . '">Edit</a></td>';
	echo '<td><a href="' . $this->url("category", array('action'=>'delete', 'id'=>$category->id), array(), true) . '" onclick="javascript: if(!confirm(\'Do you want to delete this category?\')) return false; ">Delete</a></td></tr>';
}
?>
</table>
</div>

<div id="sidebar">
<p><b>Menus</b></p>
<ul>
<li><a href="<?php echo $this->url("category", array('action' => 'add'), array(), true); ?>">Add</a></li>
<li><a href="<?php echo $this->url("category", array('action' => 'index'), array(), true); ?>">Edit</a></li>
<li><a href="<?php echo $this->url("category", array('action' => 'index'), array(), true); ?>">Delete</a></li>

</ul>
</div>

