<?php
$title = 'MiniShop - Administration - Category';
$this->headTitle($title);
?>

<table style="width:75%; text-align:center;">
<?php 
echo '<tr><td><b>Category</b></td><td><b>Product</b></td><td><b>Image</b></td><td><b>Short Desc</b></td><td><b>Details Desc</b></td><td><b>Stock</b></td><td><b>Price</b></td><td><b>Featured</b></td><td></td><td></td></tr>';

foreach($products as $product){

	echo '<tr><td>' . $product->category . '</td>';
	echo '<td>' . $product->product . '</td>';
	echo '<td><img src="../../public/img/products/' . $product->image . '" width="50" height="50" alt="'.$product->image.'"></td>';
	echo '<td>' . $product->shortdescription . '</td>';
	echo '<td>' . $product->detailsdescription . '</td>';
	echo '<td>' . $product->quantity . '</td>';
	echo '<td>' . $product->price . '</td>';
	echo '<td>' . (($product->featured==1)?'Yes':'No') . '</td>';
	echo '<td><a href="'. $this->url("product", array('action'=>'edit', 'id'=>$product->id), array(), true) . '">Edit</a></td>';
	echo '<td><a href="' . $this->url("product", array('action'=>'delete', 'id'=>$product->id), array(), true) . '" onclick="javascript: if(!confirm(\'Do you want to delete this product?\')) return false; ">Delete</a></td></tr>';
}
?>
</table>
</div>

<div id="sidebar">
<p><b>Menus</b></p>
<ul>
<li><a href="<?php echo $this->url("product", array('action' => 'add'), array(), true); ?>">Add</a></li>
<li><a href="<?php echo $this->url("product", array('action' => 'index'), array(), true); ?>">Edit</a></li>
<li><a href="<?php echo $this->url("product", array('action' => 'index'), array(), true); ?>">Delete</a></li>

</ul>
</div>

