<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to Mini Shop'), '<span class="zf-green">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('Welcome! to Mini Shop Application.')) ?></p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/zendframework/zf2" target="_blank"><?php echo $this->translate('Fork Mini Shop on GitHub') ?> &raquo;</a></p>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Product Categories') ?></h3>
            </div>
            <div class="panel-body">
                <p><ul><?php //echo $this->url('application', array('action'=>'index')); 
					foreach($categories as $category){
						
						echo '<li><a href='. $this->url("category", array("action" => "getProducts","id"=>$category->id), array(), true).'>' . $this->escapeHtml($category->category) . '</li>';
						
					}

				?></ul></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Featured Products') ?></h3>
            </div>
            <div class="panel-body">
                <p>
                <ul>
                <?php 
                
                foreach($products as $product){
                
                	echo '<li>' . $this->escapeHtml($product->product) . '</li>';
                }
                ?>                           
                </ul>
                </p>
                
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Shopping Cart') ?></uh3>
            </div>
            <div class="panel-body">
                <p>
                <ul>
                <?php 
                 
                foreach($carts as $cart){
                
                	echo '<li>' . $this->escapeHtml($cart->product) . '</li>';
                }
                ?>                           
                </ul>
                </p>
            </div>
        </div>
    </div>
</div>
